// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	NODE_VERSION: string;
	PNPM_VERSION: string;

	OAUTH_REDIRECT_API: string;
	STYTCH_PUBLIC_TOKEN: string;
}
