name: Apply OpenTofu Changes

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed
    paths:
      - "**/**.tf"
      - "**.hcl"

jobs:
  tofu-apply:
    if: github.event.pull_request.merged == true
    name: Apply OpenTofu Changes
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use OpenTofu Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.terraform/providers
          key: cache-tofu-${{ hashFiles('.terraform.lock.hcl') }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Setup just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Setup 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Download Tofu Plan
        uses: dawidd6/action-download-artifact@v3
        id: download-plan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: tofu-plan.yml
          workflow_conclusion: success
          pr: ${{ github.event.pull_request.number }}
          name: tofu-plan
      - name: OpenTofu Apply
        run: just tofu apply -no-color tofu-plan
