name: Tofu Pull Request

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]
    paths:
      - "**/**.tf"
      - "terraform.lock.hcl"
jobs:
  tofu:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: 1password/install-cli-action@v1
      - name: OpenTofu fmt
        id: fmt
        run: just tofu fmt -check -recursive -no-color
        continue-on-error: true

      - name: OpenTofu Init
        id: init
        run: just tofu init

      - name: OpenTofu Validate
        id: validate
        run: just tofu validate -no-color

      - name: OpenTofu Plan
        id: plan
        run: just tofu plan -no-color
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          FMT_OUTCOME: ${{ steps.fmt.outcome }}
          INIT_OUTCOME: ${{ steps.init.outcome }}
          VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
          PLAN_OUTCOME: ${{ steps.plan.outcome }}
          VALIDATE_STDOUT: ${{ steps.validate.outputs.stdout }}
          PLAN_STDOUT: "tofu\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { makePrComment } = await import('${{ github.workspace }}/scripts/tofu-pr-comment.mjs');
            await makePrComment();
