name: Apply OpenTofu Changes

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed
    paths:
      - "**/**.tf"
      - "**.hcl"

jobs:
  tofu-apply:
    if: github.event.pull_request.merged == true
    name: Apply OpenTofu Changes
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use OpenTofu Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.terraform/providers
          key: cache-tofu-${{ hashFiles('.terraform.lock.hcl') }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Setup just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Setup 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Find Tofu Plan
        uses: actions/github-script@v7
        id: get-plan-run-id
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getLastSuccessfulTofuPlanRunId } = await import('${{ github.workspace }}/scripts/tofu.mjs');
            return await getLastSuccessfulTofuPlanRunId({ github, context, core, glob, io, exec, require });
      - name: Download Tofu Plan
        uses: actions/download-artifact@v4
        id: download-plan
        with:
          name: tofu-plan
          path: ${{ github.workspace }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-plan-run-id.outputs.result }}
      - name: OpenTofu Apply
        run: just tofu apply -no-color ${{ steps.download-plan.outputs.download-path }}
